---
# Author:      Xuxu Xu
# Student id:  956895
# Description: deploy front end to remote instance

- name: send frontend setup to frontend server
  copy:
    src: ../../../../frontend
    dest: /home/ubuntu

- name: setup frontend
  shell:  |
    cd frontend
    sudo rm -rf node_modules
    sudo npm install
    sudo npm install kill-port-process -g
    sudo npm install forever -g

- name: start frontend
  shell:  |
    cd frontend
    sudo forever stopall 
    sudo forever start node_modules/react-scripts/scripts/start.js

