---
# Author:      Xuxu Xu
# Student id:  956895
# Description: deploy data processing program to remote instance
- name: send data processing setup to backend server
  copy:
    src: ../../../../data_processing
    dest: /home/ubuntu


- name: start backend server
  shell:  |
    cd data_processing
    sudo chmod +x run.sh
    nohup ./run.sh &
  
