#- hosts: localhost
#  vars_files:
#    - host_vars/nectar.yaml
#  gather_facts: true
#
#  roles:
#    - role: openstack-images
#    - role: openstack-volume
#    - role: openstack-security-group
#    - role: openstack-instance
#    - role: instance-allocation
#

- hosts: localhost
  roles:
    - role: add-host
#
#- hosts: database
#  gather_facts: false
#  become: true
#  vars_files:
#    - host_vars/nectar.yaml
#  vars:
#    - ansible_user: ubuntu
#    - ansible_ssh_private_key_file: ~/.ssh/xuxux.pem
#    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
#  roles:
##    - role: openstack-common
#    - role: depoly-couchdb

#- hosts: 172.26.130.158
#  gather_facts: false
#  become: true
#  vars_files:
#    - host_vars/nectar.yaml
#  vars:
#    - ansible_user: ubuntu
#    - ansible_ssh_private_key_file: ~/.ssh/xuxux.pem
#    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
#  roles:
#    #- role: openstack-common
#    - role: depoly-front-end

- hosts: crawler
  gather_facts: false
  become: true
  vars_files:
    - host_vars/nectar.yaml
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ~/.ssh/xuxux.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    #- role: openstack-common
    - role: depoly-crawler

#- hosts: 172.26.130.233
#  gather_facts: false
#  become: true
#  vars_files:
#    - host_vars/nectar.yaml
#  vars:
#    - ansible_user: ubuntu
#    - ansible_ssh_private_key_file: ~/.ssh/xuxux.pem
#    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
#  roles:
#    - role: openstack-common
#    - role: upload-20G

