---
# Author:      Xuxu Xu
# Student id:  956895
# Description: deploy crawler program to remote instance

- name: send crawler setup to crawler server
  copy:
    src: ../../../../crawler
    dest: /home/ubuntu


- name: start crawler
  shell:  |
    cd crawler
    sudo chmod +x run_search.sh
    sudo chmod +x run_stream.sh
    nohup ./run_search.sh &
    nohup ./run_stream.sh &