---
# Install dependencies on the host
- name: Install pip
  become: yes
  ansible.builtin.apt:
    name: ['python3-dev', 'python3-setuptools', 'python3-pip','curl','nodejs']
    state: latest
    update_cache: yes
  #when: ansible_distribution == "Ubuntu"
# sudo apt-get update && sudo apt-get install python3-dev python3-setuptools python-pip

- name: Update pip
  ansible.builtin.pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip && pip install openstacksdk


- name: install packages
  pip:
    name: ['tweepy','couchdb','docker','requests']
    state: latest

