---

- name: instance allocation
  shell: |
    cd ./inventory
    python3 assign_host.py


- name: Read ini file with allow_no_value
  debug:
    msg: "{{ lookup('ini', file='./inventory/_inventory.ini', section='COMP90024', allow_no_value=True) }}"
