# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: xuxux
instance_flavor: uom.mse.2c9g
_inventory: "./inventory/_inventory.ini"

# Volume
volumes:
  - vol_name: instance1-volume
    vol_size: 60
  - vol_name: instance2-volume
    vol_size: 60
  - vol_name: instance3-volume
    vol_size: 60
  - vol_name: instance4-volume
    vol_size: 60

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance-1
    volumes: ['instance1-volume']
  - name: instance-2
    volumes: ['instance2-volume']
  - name: instance-3
    volumes: [ 'instance3-volume' ]
  - name: instance-4
    volumes: [ 'instance4-volume' ]



