# Common vars
availability_zone: melbourne-qh2-uom
instance_image: aaddbad8-87d7-4ed7-9382-409b9bc42ca6
instance_key_name: xuxux
instance_flavor: uom.mse.2c9g
_inventory: "./inventory/_inventory.ini"

user: admin
pass: admin
nodes: ["172.20.0.2","172.20.0.3","172.20.0.4"]
size: 3
ports: ["5984","15984","25984"]
master_node: "{{ lookup('ini', 'database',section='database', file='./inventory/_inventory.ini',allow_no_value=True) }}"
port: 5984
other_nodes: ["172.20.0.3","172.20.0.4"]
cookie: a192aeb9904e6590849337933b000c99
# Volume
volumes:
  - vol_name: instance1-volume
    vol_size: 60
  - vol_name: instance2-volume
    vol_size: 60
  - vol_name: instance3-volume
    vol_size: 60
  - vol_name: instance4-volume
    vol_size: 60

# Security group
security_groups:
  - name: ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
    ethertype: IPv4
  - name: http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
    ethertype: IPv4
  - name: for couchdb ipv6
    description: "Demo security group for couchdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: ::/0
    ethertype: IPv6
  - name: for couchdb 5984 ipv4
    description: "Demo security group for couchdb ipv4"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
    ethertype: IPv4
  - name: for couchdb 5986 ipv4
    description: "Demo security group for couchdb ipv4"
    protocol: tcp
    port_range_min: 5986
    port_range_max: 5986
    remote_ip_prefix: 0.0.0.0/0
    ethertype: IPv4
  - name: for couchdb 5986 ipv4
    description: "Demo security group for couchdb ipv4"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
    ethertype: IPv4

# Instance
instances:
  - name: instance-1
    volumes: ['instance1-volume']
  - name: instance-2
    volumes: ['instance2-volume']
  - name: instance-3
    volumes: [ 'instance3-volume' ]
  - name: instance-4
    volumes: [ 'instance4-volume' ]



