# Common vars
availability_zone: melbourne-qh2-uom
instance_image: aaddbad8-87d7-4ed7-9382-409b9bc42ca6
instance_key_name: zhiqingw
instance_flavor: uom.mse.2c9g
_inventory: "./inventory/_inventory.ini"

user: admin
pass: admin
nodes: ["172.20.0.2","172.20.0.3","172.20.0.4"]
size: 3
master_node: 172.20.0.2
master_port: 5984

# Volume
volumes:
  - vol_name: instance1-volume
    vol_size: 60
  - vol_name: instance2-volume
    vol_size: 60
  - vol_name: instance3-volume
    vol_size: 60
  - vol_name: instance4-volume
    vol_size: 60

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance-1
    volumes: ['instance1-volume']
  - name: instance-2
    volumes: ['instance2-volume']
  - name: instance-3
    volumes: [ 'instance3-volume' ]
  - name: instance-4
    volumes: [ 'instance4-volume' ]



