- name: Add host
  ansible.builtin.add_host:
    name: '172.26.130.233'
    groups: backend

- name: Add host
  ansible.builtin.add_host:
    name: '172.26.133.101'
    groups: crawler

- name: Add host
  ansible.builtin.add_host:
    name: '172.26.130.158'
    groups: frontend

- name: Add host
  ansible.builtin.add_host:
    name: '172.26.134.66'
    groups: database



