# Author:      Xuxu Xue
# Student id:  956895
# Description: add hosts to ansible in-memory inventory

- name: Add backend host
  ansible.builtin.add_host:
    name: "{{ lookup('ini', 'backend',section='backend', file='./inventory/_inventory.ini',allow_no_value=True) }}"
    groups: backend

- name: Add crawler host
  ansible.builtin.add_host:
    name: "{{ lookup('ini', 'crawler',section='crawler', file='./inventory/_inventory.ini',allow_no_value=True) }}"
    groups: crawler

- name: Add frontend host
  ansible.builtin.add_host:
    name: "{{ lookup('ini', 'frontend',section='frontend', file='./inventory/_inventory.ini',allow_no_value=True) }}"
    groups: frontend

- name: Add database host
  ansible.builtin.add_host:
    name: "{{ lookup('ini', 'database',section='database', file='./inventory/_inventory.ini',allow_no_value=True) }}"
    groups: database



