---
#
#- name: send docker setup to database server
#  copy:
#    src: docker-compose.yml
#    dest: /home/ubuntu
#
#- name: send couchdb setup to database server
#  copy:
#    src: run.sh
#    dest: /home/ubuntu
#
#- name: setup couchdb
#  command: sh run.sh
#
#

- name: network
  become: yes
  community.docker.docker_network:
    name: couchdb_nw
    driver: bridge
    ipam_config:
      - subnet: 172.20.0.0/16
        gateway: 172.20.0.1

- name: docker start
  command: systemctl start docker.service

- name: start a container with a couchdb
  become: yes
  docker_container:
    name: "couchdb_"
    image: "ibmcom/couchdb3:3.2.1"
    ports:
      - "5984:5984"
      - "5986:5986"
      - "4369:4369"
      - "9100-9200:9100-9200"
    volumes:
      - ./data/master/data:/opt/couchdb/data
    env:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
      NODENAME: 172.20.0.2
    networks:
      - name: couchdb_nw
        ipv4_address: "172.20.0.2"

- name: start a container with a couchdb
  become: yes
  docker_container:
    name: "couch_slave1"
    image: "ibmcom/couchdb3:3.2.1"
    ports:
      - "15984:5984"
    volumes:
      - ./data/slave1/data:/opt/couchdb/data
    env:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
      NODENAME: 172.20.0.3
    networks:
      - name: couchdb_nw
        ipv4_address: "172.20.0.3"

- name: start a container with a couchdb
  become: yes
  docker_container:
    name: "couch_slave2"
    image: "ibmcom/couchdb3:3.2.1"
    ports:
      - "25984:5984"
    volumes:
      - ./data/slave2/data:/opt/couchdb/data
    env:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
      NODENAME: 172.20.0.4
    networks:
      - name: couchdb_nw
        ipv4_address: "172.20.0.4"

- name: setup couchdb
  shell:  |
    curl -X POST -H "Content-Type: application/json" http://admin:admin@172.20.0.2:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"admin", "port": 5984, "node_count": "3", "remote_node": "{{item}}", "remote_current_user": "admin", "remote_current_password": "admin" }'
    curl -X POST -H "Content-Type: application/json" http://admin:admin@172.20.0.2:5984/_cluster_setup -d '{"action": "add_node", "host":"{{item}}", "port": 5984, "username": "admin", "password":"admin"}'
  loop: "{{othernodes}}"
    


